### ISSUE TITLE
Not allowed You are not allowed to add or remove contacts to this group

### ISSUE THREAD

**Issue by KestrelWild** [CiviCooP/org.civicoop.groupprotect#1]
I'm getting this message various places around civicrm pages after installing the extension and protecting several groups. Public event participants page, member dashboard, etc. Usually happens only the first time someone visits that page.

**Comment by ErikHommel** [comment]
Thanks for reporting this @cynthiawoodard, appreciate it! I think this problem will not occur at the customer the extension was developed for as they do not use public event pages nor member dashboards. Do you do something with a protected group on some of these pages?

**Comment by ErikHommel** [comment]
Should be fixed in versione 2.2
