### ISSUE TITLE
PHP 7.4x Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by tschuettler** [CiviCooP/org.civicoop.groupprotect#12]
> Deprecated: Array and string offset access syntax with curly braces is deprecated in /opt/buildkit/build/dmaster/sites/default/files/civicrm/ext/org.civicoop.groupprotect/groupprotect.civix.php on line 155

**Comment by jensschuppe** [comment]
This is necessary for the extension to be compatible with PHP 8.
