### ISSUE TITLE
Warning regarding declaration of permission without 'label' and 'description'

### ISSUE THREAD

**Issue by TobiasVoigt** [CiviCooP/org.civicoop.groupprotect#15]
After upgrading to CiviCRM 5.71.2 my log shows this warning:

[warning] Permission 'manage protected groups' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermiss

**Comment by ErikHommel** [comment]
Thanks for reporting this @TobiasVoigt, much appreciated! Luckily it is "just" a warning. 

I assume you are familiar with how it works in open source. I have shared the work I have done for this extension and it if it is owned by anyone it is by the community. It is certainly not "mine" and I do not automatically fix any reported issues. That model is called closed source and would mean I would call this extension mine and charge a license and maintenance fee to anyone using it and use the money to fix bugs (and increase my bank account probably :-)). 

At the moment I do not have any customers using  this extension and running into this problem, and as it does not break anything I strongly suspect it will be ignored by others too.

**Comment by jensschuppe** [comment]
@TobiasVoigt Since I had this in my local stash (along with a *Civix* upgrade, see #17), I pulled both changes in for a new beta version (because I don't really use the extension). Try version [`2.5-beta1`](https://github.com/CiviCooP/org.civicoop.groupprotect/releases/tag/2.5-beta1). If that works well, maybe leave a note here so this can turn into a stable `2.5` version.

**Comment by TobiasVoigt** [comment]
Hi there,

@ErikHommel: I in no way wanted to imply that there's anybody out there who'd be responsible to fix the issue. Yet sometimes reporting an issue is the only thing I can do - be it for not having the time to dive into the code or simply for my lack of understanding the code, since I'm not a developer. In this case though I was already working on a solution - yet @jensschuppe beat me to it. ;)

I installed and (briefly) tested 2.5-beta1 and didn't experience any problems. The warnings are gone (which were clogging up the Log before since they cam every 2 seconds.)

So, thanks for responding so quickly - both of you!

Kind regards

Tobias

**Comment by ErikHommel** [comment]
Thanks @jensschuppe for fixing and @TobiasVoigt I understand and thank you once again for reporting, that is indeed a wonderful first step :-)
