### ISSUE TITLE
Support for 4.6

### ISSUE THREAD

**Issue by bkaless** [CiviCooP/org.civicoop.groupprotect#3]
I installed the extension in 4.6.14. Saving of settings of a group doesn't work anymore.

**Comment by ErikHommel** [comment]
Thanks for reporting this @bkaless!
The extension supports 4.4. The funding organization is not upgrading to 4.6 yet. As 4.6 has quite some jQuery changes I can imagine it will need fixing. Are you in a position to take this on or fund this?

**Comment by bkaless** [comment]
Thanks for explanation @ErikHommel. I'm not able to adopt the fixing. Perhaps our organization can fund a bit of it but not the whole investment :(

**Comment by ErikHommel** [comment]
I think it requires max half a day of tender loving care @bkaless. I will let you know if other organizations express interest too. I expect the funder to ignore 4.6 until 2017 (at the earliest).

**Comment by bkaless** [comment]
Hi,

my organization is now able to fund it. Are you able to send me an offer so that we can conclude a contract. My mailadress is kaless <at> forumZFD.de

Greetings
Benedikt

**Comment by ErikHommel** [comment]
Should be fixed in release 2.2
