### ISSUE TITLE
User cannot subscribe contact to a group, even if the group is not protectet

### ISSUE THREAD

**Issue by bkaless** [CiviCooP/org.civicoop.groupprotect#9]
If a user pick up a not protected group in the contact-overview page nothing happens after submitting the form. 
Perhaps this is related to this: https://github.com/CiviCooP/org.civicoop.groupprotect/issues/6 

If a user pick up a group in the contact search form which is marked as not protected, plenty of "Element 'group_id' does not exist in HTML_QuickForm::GetElement()" occurs in the log.

**Comment by jensschuppe** [comment]
@bkaless Can you confirm the changes in #11 fix those errors as well?

**Comment by bkaless** [comment]
No, it doesn't solve the problem.

I applied your patch. But the situation is still the same in my installation: 
If a user has not the role which allows him to manage protected group, he can't add a contact to a group. Protected groups are not longer listed after your patch, which is correct. But if the user chooses a Non-Protected-Group, nothing happens after submitting the "add to group"-form. The list of subscribed groups stay the same.

So actually with protected groups adding contacts to groups (no matter if protected or not) is only possible for admin-users :(

**Comment by AHowiller** [comment]
I recently made the same observations @bkaless described (v. 2.3 on CiviCRM 5.37.0 / D7)
